### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by marxcisis** [puikinsh/sufee-admin-dashboard#1]
sufee-admin-dashboard/index.html

310 rindā
<div class="chart-wrapper px-0" style="height:70px;" height="70"**/**>

attiecīgi arī 340, 371, 398, 506, rindās ir analoģiska kļūda.

Atverošā div taga beigās parasti neaizver ciet ar /> bet tikai ar >.

Lūgums labot.

**Comment by puikinsh** [comment]
Vieglāk un ātrāk būs pašam uzmest "pull request" un es to nomerdžošu.
