### ISSUE TITLE
Modify CSS

### ISSUE THREAD

**Issue by danielzt** [puikinsh/sufee-admin-dashboard#13]
Hey! Thanks for this great theme!

How to properly modify CSS? I found CSS and SCSS and created a custom_style.css to make my changes. But what the best way to do modifications? For instance "btn-primary", how to change it's colors? I changed the CSS and SCSS, is this the right way?

Thanks!

**Comment by bobykurniawan11** [comment]
well, I won't change the original file. maybe this will help you https://stackoverflow.com/a/3679478/3410328

**Comment by danielzt** [comment]
Hi Boby
I found the solution. It's here: https://getbootstrap.com/docs/4.0/getting-started/theming/

Thanks

**Comment by archiebaer** [comment]
I am delighted to hear that! (Not really) Now you've found a solution, you can close this issue.
