### ISSUE TITLE
Unable to change the horizontal layout of pie chart key

### ISSUE THREAD

**Issue by asifit** [puikinsh/sufee-admin-dashboard#20]
From where should I change the layout of Pie Chart key (i.e green green green) from horizontal to vertical?
Is there any js attribute (e.g ctx.layout ) that I am unable to find out.

https://colorlib.com/polygon/sufee/charts-chartjs.html

**Comment by puikinsh** [comment]
This template is completely free but comes with no support. Github issues are for error reporting.
